version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    command: mongod --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    restart: always

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
