services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    command: mongod --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    restart: always

  notify-app:
    build: ./app
    container_name: notify-app
    ports:
      - "3000:3000"
    networks:
      - mongo-network
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/notify

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
